### ISSUE TITLE
Planning-emailed reports

### ISSUE THREAD

**Issue by MLWilkins** [dhenry-KCI/FredCo-Post-Go-Live-#105]
The reports designed to be emailed to Mike Wilkins and Ashley Reed are not being sent.

We are suppose to get one for applications received and one for late reviews.

**Comment by dhenry-KCI** [comment]
@JuanitaMiles - follow-up on this and assign to Tara if needed.

**Comment by dhenry-KCI** [comment]
This is correspondence based on a date. Will work with Dan when he returns.

**Comment by MLWilkins** [comment]
whats going on with this ticket?  Who's court is it in?

**Comment by JuanitaMiles** [comment]
@megisys - Dan, see comments above. This issue deals with correspondence that is based on a date. Your assistance is needed.

**Comment by megisys** [comment]
I have no idea what this ticket is about

**Comment by AReed327** [comment]
"Planning - Pending Reviews by staff" Report should email weekly on Monday mornings to Mike Wilkins and Ashley Reed.
MWilkins - MWilkins@FrederickCountyMD.gov 
AReed - AReed@FrederickCountyMD.gov
![image](https://user-images.githubusercontent.com/58854333/74162071-0d8f0d80-4bee-11ea-88d7-aaade12b0fea.png)

We would also like to receive a weekly report for plans submitted. However, we are having difficulty finding the appropriate data point to use since a completeness check and reviews populated don't accurately depict the plans received. Plans have not been received until submitted and accepted with reviews assigned in PDOX. Could use plans that have a due date populated and not resulted but that would leave out plans that were submitted and completed by staff in the same week. Please advise if you can think of a way to show what has actually been received without leaving room for any projects to be missed.
AReed.

**Comment by megisys** [comment]
unassigning myself as Juanita needs to be around this and is assigning resources

**Comment by JuanitaMiles** [comment]
@megisys the configuration of correspondence around a date/time needs infor support. Based on the information Ashley has provided above, please configure the following:

**Report:** Planning - Pending Reviews by staff
**Requirement:** Automatically email the report to Mike WIlkins and Ashley Reed every Monday morning at 7am.

**Comment by megisys** [comment]
Hi Juanita,

The report will need to be changed by Tara, as it seems to have 2 date parameters. For correspondence to work the report will need the range built into it, so for today + 7 or similar. Correspondence can not pass parameters.

Thanks

Dan

**Comment by JuanitaMiles** [comment]
@TaraF Please see Dan's comments below and advise if you need any additional information to make the requested changes.

**Comment by calequin** [comment]
Did research on this with Dan @megisys . IPS does not have the ability to send over a report via batch manager as correspondence is for a single record. This type of report captures multiple records therefore the system does not have the ability to run it as a batch manager task. County would need to look at other report delivery options for this weekly task.

**Comment by JuanitaMiles** [comment]
Mike to follow up and close once confirmed.

**Comment by MLWilkins** [comment]
closing issue per Infor's comment above- not something IPS can do.
