### ISSUE TITLE
Home Occupation-not progressing to Issued and no option for Issued status

### ISSUE THREAD

**Issue by awhite806** [dhenry-KCI/FredCo-Post-Go-Live-#132]
We have had two Home occupation permits issued and generate an issue date but the status did not change from Open to Issued. When going to change the milestone to Issued, there is no Issued option. Due not having the permit with the status of Issued, we are unable to print any approval or permit issuance for customers.
![image](https://user-images.githubusercontent.com/58981029/71521725-eb386f00-288f-11ea-97dd-ca2547514bd1.png)

![image](https://user-images.githubusercontent.com/58981029/71521727-ed9ac900-288f-11ea-995e-056cd1c49ede.png)
![image](https://user-images.githubusercontent.com/58981029/71521965-ca244e00-2890-11ea-804e-c1386c9a1d56.png)

**Comment by ScottVanSooy** [comment]
Check for Issues or Filtered.

**Comment by ScottVanSooy** [comment]
There is no Issued Status.  Checking with the Team

**Comment by ScottVanSooy** [comment]
Added in Test

**Comment by ScottVanSooy** [comment]
Added to Prod

**Comment by ABonomo21** [comment]
emailed abbie to review

**Comment by awhite806** [comment]
issued status now added. but there is still no approval or official issuance in the documents.
![image](https://user-images.githubusercontent.com/58981029/71688318-a6b84200-2d6d-11ea-8e28-1dfa813307b6.png)
![image](https://user-images.githubusercontent.com/58981029/71688445-e2eba280-2d6d-11ea-9452-3f558e9895de.png)
![image](https://user-images.githubusercontent.com/58981029/71688491-eda63780-2d6d-11ea-947c-e76a26b1a259.png)

**Comment by calequin** [comment]
| Christian J. Alequin \| Consultant,   Associate   office: 470 481 7466 \| mobile: 773 350 3536   christian.alequin@infor.com\| www.infor.com/services
-- | --

**Comment by calequin** [comment]
fixing in test per email
Sent by an external sender
------------------------------------
  
Land Use is the one that has to have the inspections before it can be issued. Home occupations are issued and then the inspections can occur  

If you have any other questions, please feel free to contact me.

Thank you,

Abbie White
Senior Customer Service Technician
Permits & Inspections
30 North Market Street
Frederick, MD 21701
Phone: 301-600-6481
Awhite1@FrederickCountyMD.gov  

From: Christian Alequin <Christian.Alequin@infor.com> 
Sent: Friday, January 3, 2020 8:32 AM
To: White, Abbie <AWhite1@FrederickCountyMD.gov>
Cc: Bonomo, Ashlye <ABonomo@FrederickCountyMD.gov>
Subject: [Frederick County] Home Occupation

[EXTERNAL EMAIL] 
Hi Abbie,
I noticed on github ticket https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/issues/132 the issued date was re-added to the Inspections milestone. I was under the assumption that Home Occupations are not issued until after the inspections are completed. Is this not correct? Just wanted to check since we have the permit issued milestone happening after inspection and will require us to rearrange the milestones.

**Comment by calequin** [comment]
promote - Use_FromUnderReview_NMF
change milestone Permit Issued from 70 to 59
change default next milestone under permit issued - Inspections
change default next milestone from Awaiting Reinspections, permit issued to - Inspections
remove open status from inspections milestone
mimic test once approved.

**Comment by calequin** [comment]
waiting on @awhite806 approval before committing to prod

**Comment by awhite806** [comment]
partially fixed-The Issued milestone is there but there is still no official issuance in the documents.
![image](https://user-images.githubusercontent.com/58981029/71992544-8bcd4e00-3203-11ea-8542-6d89f9c4c81f.png)
![image](https://user-images.githubusercontent.com/58981029/71992578-95ef4c80-3203-11ea-9df0-82aec2724008.png)

**Comment by calequin** [comment]
fixed report formula AR_2 need promotion

**Comment by calequin** [comment]
needs promotion to production. please see above comments for process changes

**Comment by calequin** [comment]
promoted 1/8/2020

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/72080388-b6360e80-32ca-11ea-8058-f8df9bf1b1c0.png)
