### ISSUE TITLE
Residential Electric Minimum fee

### ISSUE THREAD

**Issue by awhite806** [dhenry-KCI/FredCo-Post-Go-Live-#137]
The residential minimum fee generated on a minor permit that was already at the minimum fee. It generated as the amount of $0 so it did not affect the fees, but it should not be there at all.
![image](https://user-images.githubusercontent.com/58981029/71531235-bb06c580-28bb-11ea-8ae0-a88c6c9a0963.png)

**Comment by ScottVanSooy** [comment]
It looks like  the ResMinFee should have been calculated to $59.  It was added on because the AddOnCondtion formula would add them unless the total was > than 59, not >= 59.  Why it added on as 0 is not correct.  Testing in IPS_TEST.  Need to verify that $59 is correct.

**Comment by ScottVanSooy** [comment]
The reason it is 0 is because of this line in the Value Calculation
Value = Value - oBuildingApp.Application.TotalUnpaidFees
Which does calculate to 0

My recommendation is to change this line

if oBldgApp.Application.TotalUnpaidFees > Value then

to  

if oBldgApp.Application.TotalUnpaidFees >= Value then

In BP_ResMinFee_AOC.

I made the change in test,  Will wait for approval to move to Prod.

**Comment by calequin** [comment]
@ScottVanSooy lets promote to prod please

**Comment by ABonomo21** [comment]
looks like this non res electrical is okay 
![image](https://user-images.githubusercontent.com/47611580/72009922-d6ab8d80-3224-11ea-966d-622f0e278c9f.png)
