### ISSUE TITLE
PLANNING - FINAL PLAT - Condition to attach a Preliminary Plan as a parent

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#154]
Need to allow a Preliminary Plat number or a Site Plan number to satisfy the attach a Preliminary Plan as a parent. (This is on FINAL Plats)

(Background: Previously we allowed combined Site/Preliminary Plans and they were entered as Site Plans when routed. For the next 4-5 years we will have some Preliminary Plans that were processed with a Site Plan application) 

The condition wording should stay the same because we are looking for the Preliminary Plan. I just need a Site Plan number to satisfy that condition when necessary. 

AReed

**Comment by calequin** [comment]
email sent to MWILKINS for clarification

**Comment by calequin** [comment]
Dustin,

Planning is down to one ready for retest (#180).  Need to use R4C test site for this retest but I am getting an error.  Sent Dan a separate email just a few minutes ago about the error message.

Two planning tickets marked Question/County assistance:
#117 doesn’t say what the question or what assistance needed is. Need to know in order to help.

Ticket is with Dustin and Ashley and I can not comment here

#76- will try to provided requested feedback today.

No Comment

Two Planning issues marked High Priority:

#184 added contacts not receiving correspondence. We are getting complaints from users about this. 

On my list for today.

**#154 this is holding up processing final plats.

This issue is a little unclear, Which Milestone are we enforcing this new change. Can you please provide a screenshot and/ or  a sample AP Number. 

Is it the Intake Review Status Check called Final PLAT - Need a Pre-Plat Attached ??**

Easy fix once I have details

Four Planning issues marked Medium: 

#76 also marked county assistance discussed above

Was unclear to us, but discussed with Christian and the Users mentioned can waive fees and reviews – Ready for Test

#105 is reports/correspondence issue

Issue is with KCI  No Comment

#180 is ready for retest, see above

System is now in Sync

#189 appears to have been looked at but not clear if it is ready for retest, promoted to prod, or both. 

Deplyed to Production overnight – Ready for retest

Thank you,

Mike

**Comment by MLWilkins** [comment]
from Christian via email:
This issue is a little unclear, Which Milestone are we enforcing this new change. Can you please provide a screenshot and/ or a sample AP Number.
Is it the Intake Review Status Check called Final PLAT - Need a Pre-Plat Attached ??**
Easy fix once I have details

Response: at intake review on final plat, must attach preliminary as child.  Need to allow  site plan to be attached in addition to Pre-plat.

**Comment by calequin** [comment]
please promote PLN_PLAT_NEEDSPREPLAT_SCF

**Comment by ScottVanSooy** [comment]
Promoted 2020-01-12

**Comment by AReed327** [comment]
Verified correct on Test application PL257720
