### ISSUE TITLE
Migration Issue 

### ISSUE THREAD

**Issue by emilypearl1** [dhenry-KCI/FredCo-Post-Go-Live-#159]
Three Issues- Migration SFD #198476

1- DW Final Inspection did not migrate from H7-IPS 
![H7 DW Final 198476](https://user-images.githubusercontent.com/58855801/71686286-c26d1980-2d68-11ea-9e9e-de0fd613ff52.PNG)
![NO DW Final migrated over from H7 198476](https://user-images.githubusercontent.com/58855801/71686288-c39e4680-2d68-11ea-93dc-524d96d21328.PNG)

2- Open or Closed Driveway Data did not migrate from H7 to IPS.  Open Driveway was entered in H7- but did not move over to IPS. 
![H7 198476 Driveway Open](https://user-images.githubusercontent.com/58855801/71686338-e7fa2300-2d68-11ea-8809-b80f6f9f6d4e.PNG)
![Details Page- Open didnt migrate 198476](https://user-images.githubusercontent.com/58855801/71686340-eb8daa00-2d68-11ea-9724-d9e842c92873.PNG)

Permit 195590- we cannot add the DW Final inspection on this permit. 

Ashlye/ Emily

**Comment by ScottVanSooy** [comment]
I'm assigning this to Dan for Review and proper assignment

**Comment by megisys** [comment]
This is right. We removed Final Inspections if not in the Final Inspections Milestone. as we had final inspections listed on in life permits in the inspection milestone. This issue is only effecting old applications with non resulted final inspections. This issue will go away in time. Can we add back to ones where they are needed. How do we know ? as this one is closed

**Comment by ABonomo21** [comment]
inspectors will add on existing permits - added driveway final for open permit
