### ISSUE TITLE
Planning - Mylar Review not showing on My Infor List

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#160]
unassigned Mylar Review should be populating on the PLANNING Review Assignments Required list for me to assign it to the planner.
I need to assign this one because the planner is waiting for it. I have attached screen shots for reference.
![image](https://user-images.githubusercontent.com/58854333/71687229-59d36c00-2d6b-11ea-92eb-baccd3716302.png)
![image](https://user-images.githubusercontent.com/58854333/71687291-7d96b200-2d6b-11ea-965d-6144846b02ba.png)

**Comment by JuanitaMiles** [comment]
@AReed327 Since you've already assigned Craig it'll be hard for me to test to confirm the problem and fix. However, two comments here:

1) If you remember these Paperwork Review applications that require assignments are their own dashboard report. (Paperwork Review Assignments Required). The decision was made a while back to keep it separate from the Under Review assignments required because I think the paperwork review should be shown on the dashboard regardless of internal or pdox status. It's hard to tell which review assignments required dashboard you are looking at in the screenshot.

2) Also, just be sure we do not miss anything, for the Paperwork Review Assignments report only, I've removed the date restriction we put on all the reports. the date was to ensure we didn't end up with a ton of really old applications that would clutter the dashboard unnecessarily. I think this will be fine for this report.

**Comment by AReed327** [comment]
Hi Juanita,

The overdue report has a lot of unassigned mylar reviews. Maybe you can use them to determine the issue. Are you saying I need another report? I think you are here tomorrow. I'd like to look at it to make sure I'm getting all of the unassigned reviews.

Thanks, Ashley R

**Comment by JuanitaMiles** [comment]
Yes there is a different dashboard report for when an application is in the Paperwork Review milestone. It cannot be combined with the standard review assignments required dashboard report because the standard one weeds out the applications that are eplans.

This Paperwork Review Assignments Required dashboard looks for applications that are in the Paperwork Review milestone and have an unassigned review. All of the applications on your overdue report are old applications that do not fit nicely into the new configuration and are not in the proper milestone to show on this dashboard. All of them except one are sitting in Awaiting Paperwork waiting for fees to be paid. The other 20009 is sitting in Admin Closure.

You’d have to use this overdue report to identify outliers like this as we phase out the old applications that do not fit the new configuration mold.

[cid:image002.jpg@01D5C18C.A0F17AA0]

**Comment by JuanitaMiles** [comment]
met with Ashley to add the correct dashboard item. She will follow up with me if anything seems incorrect moving forward. Closing ticket for now.
