### ISSUE TITLE
Planning-wrong name populating on problem resolved field and populating on reports

### ISSUE THREAD

**Issue by MLWilkins** [dhenry-KCI/FredCo-Post-Go-Live-#248]
Ashley Moore's project below shows that KVanaman is resulting/reviewing things that Ashley Moore reviewed.  This error in IPS is coming through on the report that goes out to the applicant, making it appear KVanaman is the reviewer and not Ashley Moore.  It appears that if KVanaman (and i assume anyone) processes the resubmit when it comes in the problems that get transferred from the last cycle to the new cycle have her name put on them.  

![image](https://user-images.githubusercontent.com/50637067/72612245-31667880-38fa-11ea-9c1e-2d828b203e88.png)
![image](https://user-images.githubusercontent.com/50637067/72612276-45aa7580-38fa-11ea-9a16-b7a872d46b9d.png)

![image](https://user-images.githubusercontent.com/50637067/72612295-535ffb00-38fa-11ea-8084-63d514975405.png)

**Comment by calequin** [comment]
please promote PLN_AddReviewProblems

**Comment by MLWilkins** [comment]
I think you fixed KVanaman showing up.  Below is from test:
![image](https://user-images.githubusercontent.com/50637067/72642186-c9d01d80-3939-11ea-88b2-b228ec2ac86d.png)


However, in both production (pre-fix from yesterday) and in test (post-fix) the project pending letter is still showing all of the expired problems.  Also, the review cycle isnt updating.  In test I resulted cycle 4 as resub and moved to cycle 5 but the report still says cylce 4 pending.  So the report in test and prod is off.  See 20006 

tagging Juanita and Tara in case this is a reports issue.

**Comment by JuanitaMiles** [comment]
@MLWilkins regarding the two items identified above:

Project Pending Letter showing expired problems: @TaraF will follow up via email to get additional clarification on what is currently happening and what we actually want to show on the report. She might have to adjust certain filter criteria that was previously configured.

Review Cycles on reports being off between Test and Prod: Per the current setup, because reports are only being created/updated in a single SSRS instance, the reports can only point to one set of data, which is the PROD data. Therefore, if you make a change in TEST as part of testing, the report will not see that change, it will still only reflect the information that is in prod. Which is the case for 20006. This is the established process for report development and does not appear to be a bug. If your expectation is that reports should reflect each set of data (test and prod), it will require a larger conversation with the project team to understand the feasibility of that request.

**Comment by calequin** [comment]
verified the issue above. Name is displaying correctly please deploy to production once reports are confirmed by county.
formula: PLN_AddReviewProblems

**Comment by MLWilkins** [comment]
@calequin  is this ready for retest?  Will we see the change on existing projects?

**Comment by TaraF** [comment]
@MLWilkins, @AReed327  -- please see my follow up email (sent 1/20) about the report also so that can be in sync with the changes that have happened on IPS.

**Comment by JuanitaMiles** [comment]
Meeting scheduled with Tara, Mike, Ashley for 2/3 to discuss.

**Comment by TaraF** [comment]
Met with AR 2/4/20.  Discussed items were noted, assigned.

**Comment by TaraF** [comment]
@AReed327, @MLWilkins  - this has been updated per our discussion.  Please review report updates in Prod at this time.  Please also test for old and new cases, in case we need to point to different DB fields on the back end based on a date.

**Comment by MLWilkins** [comment]
looked at half a dozen projects and everything looks great!
@JuanitaMiles I am closing this ticket since it is already fixed in prod.
