### ISSUE TITLE
SWMESD- Fees did not generate

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#257]
Grading Permit #260748

![image](https://user-images.githubusercontent.com/47611580/72900482-f4cdbf00-3cf5-11ea-97f9-5fbf166df4d7.png)

Fees did not generate eventhough the log states that "awaiting payment" 
Permit is under review. 

1/22/20202 EP/ VK

**Comment by megisys** [comment]
Hi There.

As per standards , i am not seeing expected behavior. Which fees do you believe should of added here ?

Dan

-	The County will create tickets in github and assign a priority level, DO NOT assign a person to the ticket. Where appropriate, each issue must include:
o	A screenshot
o	The AP number
o	The observed behavior
o	The expected behavior

**Comment by emilypearl1** [comment]
i have manually inserted the correct fees. 

![image](https://user-images.githubusercontent.com/58855801/72904480-f8b10f80-3cfc-11ea-879a-14859c0bde23.png)

**Comment by megisys** [comment]
It is because it wasnt created correctly and changes later

![image](https://user-images.githubusercontent.com/47392306/72906776-b8ec2700-3d00-11ea-96c5-a525b8b90773.png)

**Comment by megisys** [comment]
Also the Grading Intake page was not filled in..

**Comment by emilypearl1** [comment]
Then how did it get to under review?

**Comment by megisys** [comment]
I am not sure what magic happened here. Might want to ask Vijay..

**Comment by JuanitaMiles** [comment]
Emily and I are going to work with Vijay to ensure he has a good understanding of what information needs to be entered and when to have the appropriate fees/reviews/inspections generate. Will follow up on this ticket after we work with Vijay and discover whether there is a bug or not.
