### ISSUE TITLE
Planning-R4C upgrade-all applications-missing attachments bar

### ISSUE THREAD

**Issue by MLWilkins** [dhenry-KCI/FredCo-Post-Go-Live-#272]
missing ability for applicants to add or see attachments.  Please check all planning ap types for this functionality. 

![image](https://user-images.githubusercontent.com/50637067/73181138-a862f480-40e4-11ea-8d21-bd76ea40d311.png)

**Comment by JuanitaMiles** [comment]
IPS TEST Upgrade optimization issue. Assigning to Dan

**Comment by calequin** [comment]
fixed in test. sync \config\DocumentProviders

**Comment by ABonomo21** [comment]
attachment option is now available however, attachment was added and then rejected and there was not ability to add another attachment because it was under county review. Error occurred after the application was submitted. Permit 259419 logged in to R4C as abonomo@frederickcountymd.gov

![image](https://user-images.githubusercontent.com/47611580/73277721-8e92e180-41b8-11ea-8e99-1eeefffaa4a8.png)

![image](https://user-images.githubusercontent.com/47611580/73277737-95b9ef80-41b8-11ea-80d5-bfa2b4684a79.png)

Did a resubmit to the applicant and it still will not allow for an attachment with the same error. 

![image](https://user-images.githubusercontent.com/47611580/73277970-e4678980-41b8-11ea-93c2-257218a153dd.png)

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/73278258-56d86980-41b9-11ea-8b1a-7a69b4ef3c63.png)

**Comment by megisys** [comment]
This is a New issue. Original Issue was Attachments options missing.

**Comment by JuanitaMiles** [comment]
@ABonomo21 If your follow up attachments error issue has not been addressed yet and Dan would like a new ticket, please create a new ticket for it and close this ticket if the Attachments sections have been added appropriately added to all applicable applications.

**Comment by MLWilkins** [comment]
This is an issue on Planning and Permits.  Dan and Christian were troubleshooting this yesterday but did not hear if issue was resolved. Will create new ticket

**Comment by MLWilkins** [comment]
attachment bar is now present but is not functioning.  Created new ticket for this issue.  See #312
