### ISSUE TITLE
PLANNING - New and wrong Milestone - Affecting fees

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#335]
Project Number - SP258779
Observed behavior -Application is "Pending" This is not a status. We belive this caused fees not to show for Treasury to Process Payment
Expected behavior - Application is pending should say Application is OPEN.
Screenshot -
![image](https://user-images.githubusercontent.com/58854333/73683743-d326ed00-4690-11ea-9e92-166f422ffe08.png)
Applications with Pending as status.
![image](https://user-images.githubusercontent.com/58854333/73683870-12edd480-4691-11ea-973b-6ccbc97d3d4f.png)

**Comment by JuanitaMiles** [comment]
All of these applications have a withdrawal request log on them that pushes the application to a "Pending" status. If a withdrawal is not necessary or allowed for a particular application staff will need to manually change the status back to "Open" and likely put a stop date on the log.

Mike and Ashley will need to find the best route to have someone monitor the withdrawal requests dashboard item since Ashley is limited to the number of dashboards she currently has.

**Comment by JuanitaMiles** [comment]
@MLWilkins @AReed327 if there are follow up issues regarding the ability for applicants to submit a withdrawal request on an old H7 application, please log a separate ticket with those details.
