### ISSUE TITLE
Plumbing Permit-contacts not generating correctly when printing

### ISSUE THREAD

**Issue by awhite806** [dhenry-KCI/FredCo-Post-Go-Live-#349]
Similar to issue #298 but now when printing the plumbing permits the applicants print jumbled together in the middle of the page. assigning as High Priority and to Christian per Abonomo.
[264494.pdf](https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/files/4160901/264494.pdf)

**Comment by calequin** [comment]
assigning to Tara for reporting change of the layout. Per conversation with Juanita

**Comment by TaraF** [comment]
Assigned, in progress.

**Comment by TaraF** [comment]
@awhite806  - ready for re-test (in Prod).  Please note, this was the only APNO we saw happening for this.  The logic has been updated for all plumbing permits to show Applicants where the Capacity is not "CONTRACT".   However, that same applicant still shows on the Plumber side also because they are considered a Contractor (ISCONTRACTOR = Y).   If that part needs to be dropped out now, and only show Capacity of CONTRACT on the Plumber side, please note here and assign it back.  Thanks.

**Comment by ABonomo21** [comment]
RETESTED SAME PERMIT - STILL COMES UP WITH ADDITIONAL CONTRACTOR INFORMATION? 
![image](https://user-images.githubusercontent.com/47611580/73976628-b4299480-48f6-11ea-9e5a-440f856c29bd.png)

**Comment by TaraF** [comment]
@ABonomo21 - please read my comment above.  This was the original logic based on what i am saying above.  If you want that dropped out I can, but it will be for all, so i need to be sure the logic is correct.

**Comment by ABonomo21** [comment]
I think it would need to be dropped out. The plumber will be the primary and be listed as the contractor

we do not want the information duplicated.

**Comment by TaraF** [comment]
Latest request assigned, in progress.

**Comment by TaraF** [comment]
@ABonomo21 - the update was made as requested above.  This is a global update, so please test APNO 264494 and other plumbing permits to make sure this is the desired effect.  

264494 is only available in Prod, so this update was made for Prod and Test environments. 

Ready for re-test.

**Comment by ABonomo21** [comment]
checked in prod
