### ISSUE TITLE
Planning-summary view shows project approved but old view shows awaiting applicant revisions

### ISSUE THREAD

**Issue by MLWilkins** [dhenry-KCI/FredCo-Post-Go-Live-#362]
see example below.   Agency status is resubmit yet it went to "approved" milestone on 12/7/19.  Need to know how widespread this problem is. 

![image](https://user-images.githubusercontent.com/50637067/73967341-b505fa80-48e5-11ea-9fc8-11a0db380aab.png)

**Comment by JuanitaMiles** [comment]
Clarification here, this particular application, at least, is in the Awaiting Applicant Revisions milestone no matter if you have the summary tab turned on or not. What I think the issue here is that the application was placed in the wrong milestone at go-live (was placed in Admin Closure) which may have triggered the system to add an Approved Date to the Job Description date section. This application was then manually moved back to the appropriate Under Review milestone then progressed through to Awaiting Applicant Revisions due to the "resubmit" review result. 

![image](https://user-images.githubusercontent.com/31770504/73976293-00280980-48f6-11ea-8eca-6627c3f024da.png)

![image](https://user-images.githubusercontent.com/31770504/73976343-1b931480-48f6-11ea-9456-a4c7fa8168be.png)

**Comment by JuanitaMiles** [comment]
I don't know how widespread this scenario is...do we need to strip out the approved dates from any applications that went through this?

**Comment by MLWilkins** [comment]
@JuanitaMiles  i thought I had added a comment but guess it didnt take...This only appears on the summary view.  The old view looks fine.

Since the system is accurately showing the correct milestone and the "approved" statement doesnt seem to be hurting anything, maybe we can just monitor this for now.  Thoughts?

**Comment by JuanitaMiles** [comment]
Right what I'm saying is that, that "approved" statement you see in the new summary view header is just showing the approved data that lives on the Job description tab. They are the same thing. The only difference is how Dan designed the new summary header to show that approved date. 

But I agree, if the approved date doesn't cause any confusion internally or with applicants just close it and revisit if it becomes a problem.

**Comment by MLWilkins** [comment]
found one other example of this.  I look at the project letter report for both and nothing indicates "approved" on those letters.  I cannot confirm if "approved" appears on the portal.

**Comment by MLWilkins** [comment]
Christian confirmed on 1/7/20 morning call that the "approved" label is not appearing on portal.
