### ISSUE TITLE
Professional ID Box needs to be Editable 

### ISSUE THREAD

**Issue by awhite806** [dhenry-KCI/FredCo-Post-Go-Live-#401]
The Professional ID box needs to be editable so we can update the correct license number to the contact.
![image](https://user-images.githubusercontent.com/58981029/74362309-787b4880-4d96-11ea-945e-b71954a5ba82.png)

**Comment by calequin** [comment]
Hi Abbie, the professional cannot be edited and the system doesnt allow it to be an editable field because of the history against it. Instead the relationship can be expired from the old contact and associated to the current license holder in order for this company to be a valid license holder. This is a bit messy because of the legacy (h7) data that had these professional ID's created. A bigger discussion can be had to understand this bit more.

**Comment by ABonomo21** [comment]
Can we set up a 30 min with Christian or Dan to discuss this and what impacts it is having on our contact records.. @JuanitaMiles

**Comment by JuanitaMiles** [comment]
Meeting scheduled for 2/14 9:30am for discussion. Assigning to Ashlye and Christian to notate any outcomes of the meeting.

**Comment by calequin** [comment]
meeting rescheduled for 2/18

**Comment by JuanitaMiles** [comment]
@calequin or @ABonomo21 Please provide notes here on the outcomes/next steps of the Professional ID meeting.

**Comment by calequin** [comment]
@JuanitaMiles staff will be instructed to not use professional ID's during a search since Pro ID's are actually license numbers associated with an individual. Instead they can search for the company name and make sure the relationship exists with the company. This is a data issue and needs to be cleaned up by county staff. County will need to expire the old contacts for the company and make sure one valid contact is available. This valid contact will need to have the relationship filed out so that history remains with the contact.
Action items: 
- Dan to find out if License # can be a searchable field in the add applicants page
- Ashlye will instruct staff to not use the professional id's when searching a contact
- Possibility of wiping out professional ID's as a task to clear out bad data.

**Comment by ABonomo21** [comment]
Spoke with Dan - Will clear out all professional id in test and will not use professional id's moving forward.

**Comment by ABonomo21** [comment]
Megan will test !

**Comment by JuanitaMiles** [comment]
Once the refresh of TEST occurs on Monday 3/2, Dan will have to clear the professional id's again in Test because they will be put back with the refresh.

**Comment by ABonomo21** [comment]
clear them

**Comment by megisys** [comment]
I cleared this out of Test. PLEase do a little testing as once it is gone from production it is gone for good

**Comment by ABonomo21** [comment]
will reconsider for future phase to better evaluate the issue
