### ISSUE TITLE
Instructions Menu on Current applications 

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#402]
Can we make it so when you open a permit in the dashboard that the instructions page populates on those permits? 

![image](https://user-images.githubusercontent.com/47611580/74366942-fe9b8d00-4d9e-11ea-9407-75d7f13dacf9.png)

We are utilizing many of those instruction pages to provide direction to applicants on the a/p's that spawn and move right to the awaiting applicant resubmit  milestone such as grading and capacity for example. 

Also can you confirm that this "request a meeting" option is not active in r4c production ? 
![image](https://user-images.githubusercontent.com/47611580/74367060-34d90c80-4d9f-11ea-8fa9-522df43b5426.png)

@JuanitaMiles

**Comment by calequin** [comment]
Ashlye, capacity doesnt have any instructions therefore it is not displaying the instructions tab. The instructions are always minimized because of the rendering of the page. Unfortunately the product does not support an options of always  making it display as open instead of minimize

Also the log type were strictly in test and not in prod. I have disabled them in test just in case.

![image](https://user-images.githubusercontent.com/47603568/74370802-576a2600-4d9d-11ea-9a91-b6fbce928205.png)

**Comment by ABonomo21** [comment]
Got it :)
