### ISSUE TITLE
Minor Grading Permits - Fees

### ISSUE THREAD

**Issue by TMARTIN0926** [dhenry-KCI/FredCo-Post-Go-Live-#42]
Permit fees are populating on both the building permit as well as the grading permit. Fees should populate under one or the other. Please see building permit #258196 and grading permit #258198. This is keeping me from stage progressing several minor grading permits. 
![258196](https://user-images.githubusercontent.com/58991985/71027796-f514e200-20d9-11ea-984d-a2c42dcdda26.PNG)
![258198](https://user-images.githubusercontent.com/58991985/71027804-f80fd280-20d9-11ea-86fc-33ef7cba9809.PNG)

**Comment by megisys** [comment]
@ABonomo21  did these get manually added ?

**Comment by TMARTIN0926** [comment]
Dan – It sounds like these were manually added. I was told this morning that this will not be the case moving forward.

**Comment by ABonomo21** [comment]
The fees will need to be waived on the grading permit until such time we allow applicants to submit the applications on r4c. again this is only temporary because once applicant can submit on r4c they will pay for each permit separately. we can also send a notice out to our builders to start getting separate checks for grading and driveway permits if they are planning to submit an application in person at the county.

**Comment by TMARTIN0926** [comment]
I think we need to reach out to the applicants to eliminate errors and confusion regarding fees.
