### ISSUE TITLE
STOP NOT log was added and notifications still went to customer.

### ISSUE THREAD

**Issue by awhite806** [dhenry-KCI/FredCo-Post-Go-Live-#449]
The STOP NOT log was added to this permit and the applicant notification still went to the customer
H257942
![image](https://user-images.githubusercontent.com/58981029/75476044-e4011080-5967-11ea-9eb9-0e15edd47693.png)

**Comment by JuanitaMiles** [comment]
I have a feeling this might have happened because there is another stopnot log on this application with a stop date. Perhaps the formula only looks to see if there is a stop date without taking into consideration that another one was added? For tracking purposes it would be ideal for the system to recognize this so staff can see the periods of time when notifications were set to not send.

**Comment by awhite806** [comment]
this happened again Building permit #205272, in the meantime should we delete the previous stop log so the customer does not get all these incorrect emails?? need to check with @ABonomo21 
![image](https://user-images.githubusercontent.com/58981029/75703321-3d798000-5c85-11ea-9fa3-372c11ae7dfa.png)

**Comment by megisys** [comment]
Hi There, I changed for USE. Not all Modules. If accepted for USE. change will be made to all modules.

Dan

**Comment by megisys** [comment]
SendNotifications to be promoted and adjusted on acceptance

**Comment by JuanitaMiles** [comment]
Worked for Land Use L257971. @megisys apply solution to other modules.

![image](https://user-images.githubusercontent.com/31770504/77003528-e84f9680-6933-11ea-975f-d746ccc592c2.png)
