### ISSUE TITLE
Electrical Permit - Permit Official Issuance Report Formatting

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#491]
Creating on behalf of AB. Customer sent a notice that the formatting of the Electrical Permit Official Issuance report appears "off". The Property Information has been pushed down to a second page, when it is usually continues on the first page.

[Electrical_Permit_-_Official_Issuance_HANSEN8_20200317_104155737.pdf](https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/files/4344924/Electrical_Permit_-_Official_Issuance_HANSEN8_20200317_104155737.pdf)

**Comment by TaraF** [comment]
Assigned - investigating.

**Comment by TaraF** [comment]
@JuanitaMiles / @ABonomo21 

For Electrical permit 268450 in production, it is not showing correctly because there is no license contact.  The report expects to see under applicants, a License Contact, with an ELEC license, per our discussions and as agreed upon.  This particular one is the only case I am seeing that doesn't follow those rules.

I think a simple fix would be to change the "Other Contact" to a "License Contact" because it appears to have an ELEC and a PLUMB license associated to it.
