### ISSUE TITLE
Zoning Cert Issuance correspondence

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#588]
Zoning Certificate once issued is adding the official issuance document (which generates blank) and should be adding the Zoning Certificate document. 

see example 192611 in production 
generating this report
![image](https://user-images.githubusercontent.com/47611580/85041880-8253f480-b158-11ea-8ed8-75d6038b7849.png)
blank
![image](https://user-images.githubusercontent.com/47611580/85041890-8718a880-b158-11ea-954b-3518985fe66d.png)
should add this report labeled zoning cert in the documents menu
![image](https://user-images.githubusercontent.com/47611580/85041908-8e3fb680-b158-11ea-8b99-8c349b2fc1eb.png)
![image](https://user-images.githubusercontent.com/47611580/85041929-939d0100-b158-11ea-9381-61b9e88fdcb0.png)

**Comment by TaraF** [comment]
Looking into this issue.

**Comment by TaraF** [comment]
@ABonomo21 - I have double checked all the code for correspondence related to Zoning Certificates, and checked all of the places it hooks up in the system, and everything looks to be correct.  Just noting also, nothing has been changed by KCI on this front since Go-Live in December.

Please see a newer Zoning Certificate, 280816 (in production), which appears that correspondence / attachments worked as expected.  It was issued on 6/22/2020, and the attachment ran on 6/22/2020 and generated correctly, as the zoning certificate. 

The permit 192611 is somewhat old - processed 4/12/19, issued 4/29/19.  Please keep in mind Production / Go Live was at the beginning of Dec 2019, so this was issued prior to that, so that is likely one of the problems.  Another oddity about this permit is that it had generated things not associated to a Zoning Certificate application type on 6/17/2020.  It almost seems like someone changed the application type to something different on that date and then changed it back (although, I am unsure if that is even possible??).  

Zoning Certificate Application types, to my knowledge, only have one correspondence type set, on the milestone of "Permit Issued" and that is for the Official Zoning Certificate to generate, email, and attach to the application (upon issuance). 

Please review all of my above information, and let me know if anything doesn't sound correct to you.  If it is just a problem with this one AP#, I would defer to the Infor team to support looking into how they could resolve this issue for you.

APNO 280816:
![image](https://user-images.githubusercontent.com/4104464/85583900-a9a13a80-b60c-11ea-9e89-a3003af2b1a3.png)


@JuanitaMiles  - tagging you for reference.

**Comment by JuanitaMiles** [comment]
@TaraF Thank you for looking into this, it was very helpful.

@ABonomo21 I've also confirmed Tara's statement, that newer applications appear to be generating the correct correspondence. It's hard to tell why the extra building permit correspondence added but it may have been part of the batch job work that Dan and IIT have been working through this month.

My recommendation is to add the Zoning Cert manually to this application so it can be made available to the applicant. I would rather a manual add on this one to avoid any additional forced milestone movement that could cause us more headache.

**Comment by JuanitaMiles** [comment]
I think I might have had a revelation...
@megisys Dan can you confirm whether or not the batch job for permit extensions ALWAYS sends the Building Permit Official Issuance report no matter the permit type (aside from grading & driveway of course). Zoning Certificate should not receive the typical Building Permit Official Issuance. It has it's own issuance report: Zoning Certificate. 

On Permit 192611 the extension log/review dates correspond pretty closely to when the extension/official issuance attachments were added. 6/16-6/17 I feel like this is probably why we are seeing the incorrect issuance report being generated.

The original Zoning cert didn't generate because it was issued prior to go live, outside of the new correspondence process.

**Comment by ABonomo21** [comment]
moved
