### ISSUE TITLE
extension - retroactive 

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#59]
retroactive extension granted should have changes the status back to open - 

it changed the date and added the fee but status needed to be changed. 

![image](https://user-images.githubusercontent.com/47611580/71111470-85fdc300-2197-11ea-8e80-f64b31fbd50b.png)

**Comment by calequin** [comment]
Spoke to Dan about this one. If an application has already expired or closed then the milestone needs to be supervisor override to the correct milestone. A log for cexp needs to be added to clear out the expired status. This is mostly for old applications since the new ones will have a 30 day notice that will give the consituent a heads up before it expires.

**Comment by ABonomo21** [comment]
have to reopen in milestone change first
