### ISSUE TITLE
Planning - DUSWM Application - DUSWM review should be 3 weeks 

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#590]
Project Number - example D260082
Observed behavior - Due dates not setting to 21 days (3 week) on DUSWM Review
Expected behavior - Should be 3 weeks
Screenshot -
![image](https://user-images.githubusercontent.com/58854333/85619515-68228680-b630-11ea-9385-7499b2a181e6.png)

**Comment by JuanitaMiles** [comment]
@AReed327 I just made this change myself in TEST to confirm it works. I believe the holiday is accounted for in my example which is why I'm getting a due date of 7/24 when the review was added on 6/24 in my screenshot below. I will make the same update in Production.

![image](https://user-images.githubusercontent.com/31770504/85623877-0f0a2100-b637-11ea-8acc-b8bb70884740.png)
![image](https://user-images.githubusercontent.com/31770504/85623927-1f220080-b637-11ea-9017-f835114f416b.png)

**Comment by JuanitaMiles** [comment]
Due date time frame in production has been set to ALWAYS be 3 weeks no matter the review cycle. If you want to implement the tiered review cycle due dates (3,2,1 week), we will require assistance from Dan as the configuration for this is more involved.

![image](https://user-images.githubusercontent.com/31770504/85624760-62c93a00-b638-11ea-8387-9d44c87b9a0c.png)

**Comment by JuanitaMiles** [comment]
@AReed327 if satisfied with this 21 day time frame for all review cycles, you can close the ticket.

**Comment by AReed327** [comment]
Maybe it was just not populating 3 weeks in test. I thought I commented on the 21 days previously. Closing ticket as appears correct in PROD.
