### ISSUE TITLE
Fire Permit- Final Inspection 

### ISSUE THREAD

**Issue by emilypearl1** [dhenry-KCI/FredCo-Post-Go-Live-#79]
Fire permit 197476 
Fire inspection passed on 12/16/19 by KConnor
A 4th final inspection generated - Permit stuck in Issued/ Final Inspection Status
This is happening on all fire permits that I see a final inspection has already passed. 

Ashlye has already reviewed.

**Comment by emilypearl1** [comment]
[fire 197476.pdf](https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/files/3985306/fire.197476.pdf)

EP 12/19/19

**Comment by emilypearl1** [comment]
also see the logs for permit 202049 -same thing occured

**Comment by calequin** [comment]
this was part of go live in life issue. Since hansen 7 had finals in the inspections milestone these applications migrated into inspections. Therefore a final already existed. once it went into the final inspection milestone automatically it added the final again. Even thought the old final had passed.

**Comment by ABonomo21** [comment]
christian can you call emily and i today about this one.

**Comment by ABonomo21** [comment]
spoke to Kim- this migration issue is phasing out.
